export const actionTypes = {
  GET_THINGS_REQUEST: 'GET_THINGS_REQUEST',
  GET_THINGS_SUCCESS: 'GET_THINGS_SUCCESS',
  GET_WORD_REQUEST: 'GET_WORD_REQUEST',
  INCREMENT_SCORE: 'INCREMENT_SCORE',
  UPDATE_WINNER: 'UPDATE_WINNER',
}